@baseUrl = http://localhost:5000

###Get Health
GET {{baseUrl}}/health

###Get offline routes health
GET {{baseUrl}}/offlinehealth

###test login wrapper
GET {{baseUrl}}/loginTest

###get current user
GET {{baseUrl}}/getcurrentuser

###get global user's characters
GET {{baseUrl}}/getglobaluserchars

################### user route testing #####################
###Create new user
POST {{baseUrl}}/register
Content-Type: application/json

{
    "inputUsername": "Hangyodon11",
    "inputPassword": "hangyodon",
    "verifyInputPassword": "hangyodon"
}

###User login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "inputUsername": "Hangyodon11",
    "inputPassword": "hangyodon"
}

###Log out of current user and wipe global user
POST {{baseUrl}}/logout

#admin tools
###Get All Users
GET {{baseUrl}}/getallusers

################### Add new user character to user #####################

###create new character in offline database with base stats
POST {{baseUrl}}/offline/addnewchar
Content-Type: application/json

{
    "inputUserCharID": "16"
}

###remove character from owned characters in local db
POST {{baseUrl}}/offline/dropchar
Content-Type: application/json

{
    "inputUserCharID": "16"
}

#######create buttons to iterate on existing characters

##track/untrack char
##flip flop or button replace?
POST {{baseUrl}}/offline/fliptracking
Content-Type: application/json

{
    "inputUserCharID": "16"
}

####front end remember to only activate on negative edge
##raise normal attack level
POST {{baseUrl}}/offline/tapraisenalevel
Content-Type: application/json

{
    "inputUserCharID": "16"
}
##numerically change normal attack level

##raise skill level
##numerically change skill level

##raise burst level
##numerically change burst level

##################sync offline db with online regions
GET {{baseUrl}}/syncdown

###
GET {{baseUrl}}/upload
