@baseUrl = http://localhost:5000

###Get Health
GET {{baseUrl}}/health

###test login wrapper
GET {{baseUrl}}/loginTest

###get current user
GET {{baseUrl}}/getcurrentuser

###get global user's characters
GET {{baseUrl}}/getglobaluserchars

################### user route testing #####################
###Create new user
POST {{baseUrl}}/register
Content-Type: application/json

{
    "inputUsername": "Cheesey331",
    "inputPassword": "password",
    "verifyInputPassword": "password"
}

###User login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "inputUsername": "Cheesey331",
    "inputPassword": "password"
}

###Log out of current user and wipe global user
POST {{baseUrl}}/logout

#admin tools
###Get All Users
GET {{baseUrl}}/getallusers

################### Add new user character to user #####################


##################sync offline db with online regions
GET {{baseUrl}}/syncdown
